
name: Release

env:
  TZ: Asia/Shanghai

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run integration script
        run: ./main.bat

      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: module
          path: Sarasa-Gothic-Font-Magisk-Module.zip

  nightly-release:
    permissions: write-all
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/') != true
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: module

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly-release"
          prerelease: true
          title: "test Build"
          files: |
            Sarasa-Gothic-Font-Magisk-Module.zip

  release:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: module

      #- name: Unzip the artifact
      #  run: |
      #    mkdir temp
      #    unzip mod.zip -d temp

      - name: Release Action
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Sarasa-Gothic-Font-Magisk-Module.zip
          body_path: changelog.md
